name: QualiBooth Code Analysis1
on:
  push:
    branches: ["main", "develop", "gh-pages"]
  pull_request:
    branches: ["main"]
jobs:
  accessibility-scan:
    name: Accessibility Code Scan1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run QualiBooth Code Analysis
        uses: docker://ghcr.io/qualibooth/qualibooth-action:latest
        env:
          QUALIBOOTH_ORG_UUID: "06ba6bb5-799a-4a01-8570-ae812eedd03e"
          QUALIBOOTH_REPO: "ata-2"
          QUALIBOOTH_SHA: ${{ github.sha }}
          QUALIBOOTH_BRANCH: ${{ github.ref_name }}
          QUALIBOOTH_SCAN_PATHS: tests
          QUALIBOOTH_PROJECT_TYPE: html
          QUALIBOOTH_API_URL: "https://pipelinein.prod.qualibooth.com"

