name: QualiBooth Code Analysis
on:
  push:
    branches: ["main", "develop", "gh-pages"]
  pull_request:
    branches: ["main"]
jobs:
  accessibility-scan:
    name: Accessibility Code Scan
    runs-on: ubuntu-latest
    steps:
      - name: Run QualiBooth Code Analysis
        uses: docker://ghcr.io/qualibooth/qualibooth-action:v1.0.7
        env:
          QUALIBOOTH_ORG_UUID: a0f273d0-9765-403e-98dc-7bbb59c70c60
          QUALIBOOTH_REPO: ${{ github.repository }}
          QUALIBOOTH_SHA: ${{ github.sha }}
          QUALIBOOTH_BRANCH: ${{ github.ref_name }}
          QUALIBOOTH_API_URL: https://pipelinein.dev.qualibooth.com
          QUALIBOOTH_PROJECT_TYPE: "html"
