name: QualiBooth Code Analysis1
on:
  push:
    branches: ["main", "develop", "gh-pages"]
  pull_request:
    branches: ["main"]
jobs:
  accessibility-scan:
    name: Accessibility Code Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run QualiBooth Code Analysis
        uses: docker://ghcr.io/qualibooth/qualibooth-action:latest
        env:
          QUALIBOOTH_ORG_UUID: "e7d4b02c-bca8-463c-972f-2770f741ea30"
          QUALIBOOTH_REPO: ${{ github.repository }}
          QUALIBOOTH_SHA: ${{ github.sha }}
          QUALIBOOTH_BRANCH: ${{ github.ref_name }}
          QUALIBOOTH_SCAN_PATHS: tests
          QUALIBOOTH_PROJECT_TYPE: "html"

